// ──────────────────────────────────────────────────────────────────────────
// updater.ts — full-app auto-update via electron-updater (main process only)
//
// Replaces the former custom web-UI hot-swap engine (signed zip manifests,
// version pointers, health gate + rollback watchdog). Updates now ship as
// complete app releases on GitHub; electron-updater reads the release feed
// (latest.yml / latest-linux.yml, generated by electron-builder because
// electron-builder.yml declares a `publish` provider), downloads the new
// installer in the background, and installs it on restart.
//
// Platform support: Windows (NSIS) and Linux (AppImage). macOS auto-update
// requires a code-signed app (Squirrel.Mac refuses unsigned bundles), so it
// is disabled there until we ship signed/notarized builds — mac users update
// by downloading the DMG from GitHub Releases.
//
// Channels: electron-updater's default behavior — a stable install only sees
// stable releases; an install whose own version carries a prerelease suffix
// (e.g. 0.7.0-beta.1) also sees prereleases (allowPrerelease defaults from
// the current version). No separate channel setting to configure or drift.
// ──────────────────────────────────────────────────────────────────────────

import { app } from "electron";
// electron-updater is CJS; default-import + destructure for ESM interop.
import electronUpdater from "electron-updater";
import type { UpdaterStatus, UpdaterEventPayload } from "./bridge-types";

const { autoUpdater } = electronUpdater;

export const MAC_UPDATE_HINT =
  "Automatic updates aren't available on macOS yet — download the latest release from GitHub.";

/**
 * Auto-update is active only in a packaged build with no vite dev server and
 * on a platform whose artifact format electron-updater can update unsigned.
 */
export function updaterSupported(): boolean {
  return (
    app.isPackaged &&
    !process.env.VITE_DEV_SERVER_URL &&
    process.platform !== "darwin"
  );
}

// In-memory status mirror for the renderer's getStatus() polling. The
// authoritative state lives inside electron-updater; this only tracks what
// the UI needs between events.
let phase: UpdaterStatus["phase"] = "idle";
let lastError: string | null = null;
let availableVersion: string | null = null;
let downloadedVersion: string | null = null;
let lastCheckAt: string | null = null;

let wired = false;
let checkInFlight: Promise<void> | null = null;

export function getStatus(): UpdaterStatus {
  return {
    currentVersion: app.getVersion(),
    stagedVersion: downloadedVersion,
    availableVersion,
    phase,
    lastCheckAt,
    error: lastError,
  };
}

function wireEvents(onEvent: (event: UpdaterEventPayload) => void): void {
  if (wired) return;
  wired = true;
  autoUpdater.autoDownload = true;
  // If the user quits without clicking the banner, install the downloaded
  // update on the way out rather than re-downloading next launch.
  autoUpdater.autoInstallOnAppQuit = true;
  autoUpdater.on("update-available", (info) => {
    phase = "downloading";
    availableVersion = info.version;
    onEvent({ type: "available", version: info.version });
  });
  autoUpdater.on("update-not-available", () => {
    phase = "idle";
    availableVersion = null;
    onEvent({ type: "uptodate" });
  });
  autoUpdater.on("update-downloaded", (info) => {
    phase = "staged";
    downloadedVersion = info.version;
    onEvent({ type: "staged", version: info.version });
  });
  autoUpdater.on("error", (err) => {
    phase = "error";
    lastError = err instanceof Error ? err.message : String(err);
    onEvent({ type: "error", message: lastError });
  });
}

/**
 * Check the GitHub release feed and, when a newer version exists, download it
 * before resolving — so a manual "Check for updates" resolves with
 * stagedVersion already set and the renderer shows the restart banner
 * immediately instead of a misleading "up to date" toast mid-download.
 * Concurrent calls (manual check racing the launch check) share one run.
 * Never throws; failures land in phase/error and the "error" event.
 */
export async function checkForUpdates(
  onEvent: (event: UpdaterEventPayload) => void
): Promise<UpdaterStatus> {
  if (!updaterSupported()) return getStatus();
  wireEvents(onEvent);
  if (!checkInFlight) {
    phase = "checking";
    lastError = null;
    lastCheckAt = new Date().toISOString();
    checkInFlight = (async () => {
      const result = await autoUpdater.checkForUpdates();
      if (result?.downloadPromise) await result.downloadPromise;
    })()
      .catch((err) => {
        // The "error" listener above already recorded phase/lastError for
        // emitter-reported failures; this also catches pre-emitter throws.
        phase = "error";
        lastError = err instanceof Error ? err.message : String(err);
      })
      .finally(() => {
        checkInFlight = null;
      });
  }
  await checkInFlight;
  return getStatus();
}

/**
 * Quit and install the downloaded update. Only meaningful after an
 * "update-downloaded" event (stagedVersion set).
 */
export function installNow(): { applied: boolean; version?: string } {
  if (!updaterSupported() || !downloadedVersion) return { applied: false };
  const version = downloadedVersion;
  // isSilent=false keeps the NSIS UI defaults; isForceRunAfter=true relaunches
  // the app when the install completes.
  autoUpdater.quitAndInstall(false, true);
  return { applied: true, version };
}
