// ──────────────────────────────────────────────────────────────────────────
// updater.ts — full-app auto-update via electron-updater (main process only)
//
// Replaces the former custom web-UI hot-swap engine (signed zip manifests,
// version pointers, health gate + rollback watchdog). Updates now ship as
// complete app releases on GitHub; electron-updater reads the release feed
// (latest.yml / latest-linux.yml, generated by electron-builder because
// electron-builder.yml declares a `publish` provider), downloads the new
// installer on demand, and installs it on restart.
//
// Platform support: Windows (NSIS) and Linux AppImage (AppImageUpdater
// requires the app to actually be running from an .appimage — a Linux
// install that isn't packaged as an AppImage is treated as unsupported, same
// as macOS, rather than letting AppImageUpdater throw). macOS auto-update
// requires a code-signed app (Squirrel.Mac refuses unsigned bundles), so it
// is disabled there until we ship signed/notarized builds — mac users update
// by downloading the DMG from GitHub Releases.
//
// Channels: electron-updater's default behavior — a stable install only sees
// stable releases; an install whose own version carries a prerelease suffix
// (e.g. 0.7.0-beta.1) also sees prereleases (allowPrerelease defaults from
// the current version). No separate channel setting to configure or drift.
//
// Downloads are user-consented: autoDownload is OFF. A check that finds an
// update stops at phase "available"; the renderer shows a Download
// affordance, and only an explicit download() call fetches the installer
// (phase "downloading" -> "staged"). This avoids silently pulling 100+MB on
// a metered connection. autoInstallOnAppQuit stays on so a staged update the
// user never clicked "Restart & update" for still applies on quit.
// ──────────────────────────────────────────────────────────────────────────

import { app } from "electron";
// electron-updater is CJS; default-import + destructure for ESM interop.
import electronUpdater from "electron-updater";
import type { UpdaterStatus, UpdaterEventPayload } from "./bridge-types";

const { autoUpdater: realAutoUpdater } = electronUpdater;

/**
 * The slice of electron-updater's AutoUpdater surface this module drives.
 * Typed structurally (not `typeof AutoUpdater`) so a test double only has to
 * implement what's actually used — an EventEmitter plus the two RPCs.
 */
export interface AutoUpdaterLike {
  autoDownload: boolean;
  autoInstallOnAppQuit: boolean;
  on(event: "update-available", listener: (info: { version: string }) => void): unknown;
  on(event: "update-not-available", listener: () => void): unknown;
  on(event: "update-downloaded", listener: (info: { version: string }) => void): unknown;
  on(event: "error", listener: (err: unknown) => void): unknown;
  checkForUpdates(): Promise<{ downloadPromise?: Promise<unknown> } | null>;
  downloadUpdate(): Promise<unknown>;
  quitAndInstall(isSilent?: boolean, isForceRunAfter?: boolean): void;
}

/** Injectable dependencies — a plain object, not a DI framework (M2). */
export interface UpdaterDeps {
  autoUpdater: AutoUpdaterLike;
}

const defaultDeps: UpdaterDeps = { autoUpdater: realAutoUpdater as unknown as AutoUpdaterLike };

let activeAutoUpdater: AutoUpdaterLike = defaultDeps.autoUpdater;

const MAC_UPDATE_HINT =
  "Automatic updates aren't available on macOS yet — download the latest release from GitHub.";
const LINUX_UPDATE_HINT =
  "Automatic updates aren't available for this install — download the latest release from GitHub.";

const NETWORK_ERROR_PATTERN =
  /ENOTFOUND|ECONNREFUSED|ECONNRESET|ETIMEDOUT|ENETUNREACH|EAI_AGAIN|net::ERR_|getaddrinfo|network error|NetworkError|fetch failed|net::/i;

function isNetworkError(message: string): boolean {
  return NETWORK_ERROR_PATTERN.test(message);
}

/**
 * Map a raw electron-updater/Node error string to a message a non-technical
 * author can act on. The raw string is never shown to the user — callers
 * that want it for diagnostics log it themselves (main-process log only).
 */
function friendlyMessage(raw: string, op: "check" | "download"): string {
  const verb = op === "download" ? "download the update" : "check for updates";
  if (isNetworkError(raw)) {
    return `Couldn't ${verb}. Check your internet connection and try again.`;
  }
  return op === "download"
    ? "Update download failed. You can download the latest version from GitHub."
    : "Update check failed. You can download the latest version from GitHub.";
}

/**
 * Auto-update is active only in a packaged build with no vite dev server and
 * on a platform whose artifact format electron-updater can update unsigned:
 * Windows, or Linux when actually running as an AppImage (AppImageUpdater
 * throws on a non-AppImage Linux install, e.g. a raw unpacked dir or a distro
 * package — those are unsupported, not a bug to surface).
 */
export function updaterSupported(): boolean {
  if (!app.isPackaged || process.env.VITE_DEV_SERVER_URL) return false;
  if (process.platform === "darwin") return false;
  if (process.platform === "linux" && !process.env.APPIMAGE) return false;
  return true;
}

// In-memory status mirror for the renderer's getStatus() polling. The
// authoritative state lives inside electron-updater; this only tracks what
// the UI needs between events. `downloadedVersion` deliberately survives a
// later "update-not-available" check: the downloaded installer still applies
// on quit (autoInstallOnAppQuit), so reporting it staged stays truthful.
let phase: UpdaterStatus["phase"] = "idle";
let lastError: string | null = null;
let downloadedVersion: string | null = null;
let availableVersion: string | null = null;

let emitEvent: (event: UpdaterEventPayload) => void = () => {};
let checkInFlight: Promise<void> | null = null;
// Upgraded to false (never back to true) if any concurrent caller of
// checkForUpdates() during the in-flight run cares about seeing the result —
// see checkForUpdates() for the sharing rationale.
let checkInFlightSilent = true;
let downloadInFlight: Promise<void> | null = null;
// Read by the "error" listener to decide whether a failure should latch a
// user-visible error (H1): a silent background check that fails offline must
// not strand the app in phase "error" for the rest of the session.
let currentOperationSilent = false;
// Which operation the shared "error" listener should attribute a failure to
// — check and download errors need different user-facing wording.
let currentOperation: "check" | "download" = "check";
let lastCheckAt = 0;

export function getStatus(): UpdaterStatus {
  return {
    currentVersion: app.getVersion(),
    stagedVersion: downloadedVersion,
    availableVersion,
    phase,
    error: lastError,
  };
}

/**
 * Wire the electron-updater listeners and the single event sink for renderer
 * push events. Call ONCE from main.ts before any checkForUpdates() call —
 * events always flow to this sink, never to a per-call callback (a per-call
 * parameter would advertise routing the implementation can't honor).
 *
 * `deps` is an injection seam for tests: a fake EventEmitter-based
 * AutoUpdaterLike can be passed so this module never touches the real
 * electron-updater singleton (which makes real network calls) or a bare
 * `electron` import (which isn't a real Electron runtime under `bun test`).
 */
export function initUpdater(
  onEvent: (event: UpdaterEventPayload) => void,
  deps: UpdaterDeps = defaultDeps,
): void {
  emitEvent = onEvent;
  activeAutoUpdater = deps.autoUpdater;
  // Downloads are user-consented (M1) — see the module banner comment.
  activeAutoUpdater.autoDownload = false;
  // If the user quits without clicking the banner, install the downloaded
  // update on the way out rather than re-downloading next launch.
  activeAutoUpdater.autoInstallOnAppQuit = true;
  activeAutoUpdater.on("update-available", (info) => {
    phase = "available";
    availableVersion = info.version;
    emitEvent({ type: "available", version: info.version });
  });
  activeAutoUpdater.on("update-not-available", () => {
    phase = "idle";
    availableVersion = null;
    emitEvent({ type: "uptodate" });
  });
  activeAutoUpdater.on("update-downloaded", (info) => {
    phase = "staged";
    downloadedVersion = info.version;
    availableVersion = null;
    emitEvent({ type: "staged", version: info.version });
  });
  activeAutoUpdater.on("error", (err) => {
    const raw = err instanceof Error ? err.message : String(err);
    console.error("[updater] electron-updater error:", raw);
    if (currentOperationSilent && isNetworkError(raw)) {
      // H1: a silent background check that failed because the user is
      // offline is not an error worth latching — try again next time
      // (launch, or the throttled focus re-check in main.ts). Also release
      // the focus-recheck throttle: a failed check must not consume the
      // window, or coming back online within it would never retry.
      phase = "idle";
      lastError = null;
      lastCheckAt = 0;
      return;
    }
    phase = "error";
    lastError = friendlyMessage(raw, currentOperation);
  });
}

/**
 * Check the GitHub release feed. Resolves once the CHECK completes — updates
 * are no longer auto-downloaded (M1), so the resolved status is one of:
 * "available" (found, awaiting a download() call), "staged" (an earlier
 * download already completed), "error", or "idle" (up to date).
 *
 * `silent: true` marks a background/automatic check (launch, focus
 * re-check): a network-type failure resets to "idle" instead of latching a
 * user-visible error (H1). User-initiated checks (the `updater:check` IPC)
 * omit `silent` and always get full error reporting.
 *
 * Concurrent calls share one run; if ANY caller during that run is
 * non-silent, the run is treated as non-silent (a user who explicitly asked
 * "check now" must see the real result even if a background check kicked
 * off microseconds earlier).
 *
 * Never throws.
 */
export async function checkForUpdates(options: { silent?: boolean } = {}): Promise<UpdaterStatus> {
  const silent = options.silent ?? false;
  if (!updaterSupported()) {
    // Manual checks on an unsupported platform get an honest pointer at
    // GitHub Releases instead of a silent idle status that reads as "you're
    // up to date". Silent (background) checks never reach here — main.ts
    // only calls checkForUpdates() from a spot gated on updaterSupported().
    if (!silent && app.isPackaged) {
      if (process.platform === "darwin") {
        phase = "error";
        lastError = MAC_UPDATE_HINT;
      } else if (process.platform === "linux" && !process.env.APPIMAGE) {
        phase = "error";
        lastError = LINUX_UPDATE_HINT;
      }
    }
    return getStatus();
  }
  if (!checkInFlight) {
    checkInFlightSilent = silent;
    currentOperationSilent = silent;
    currentOperation = "check";
    if (!silent) {
      phase = "checking";
      lastError = null;
    }
    lastCheckAt = Date.now();
    checkInFlight = (async () => {
      await activeAutoUpdater.checkForUpdates();
      // No update → the "update-not-available" listener already set idle.
      // An update → the "update-available" listener already set "available"
      // (download is user-triggered, not started here).
    })()
      .catch((err) => {
        // The "error" listener above already recorded phase/lastError for
        // emitter-reported failures; this also catches pre-emitter throws
        // (e.g. checkForUpdates() itself rejecting).
        const raw = err instanceof Error ? err.message : String(err);
        if (checkInFlightSilent && isNetworkError(raw)) {
          phase = "idle";
          lastError = null;
          // Release the focus-recheck throttle — see the "error" listener.
          lastCheckAt = 0;
        } else {
          phase = "error";
          lastError = friendlyMessage(raw, "check");
        }
      })
      .finally(() => {
        checkInFlight = null;
      });
  } else if (!silent) {
    // A non-silent caller joined an in-flight (possibly silent) run —
    // upgrade so its error handling reports honestly.
    checkInFlightSilent = false;
    currentOperationSilent = false;
  }
  await checkInFlight;
  return getStatus();
}

/**
 * Download the update found by the last check (phase "available"). Always
 * treated as a user-initiated (non-silent) operation — a download is only
 * ever started by an explicit click. Single-flight guarded like
 * checkForUpdates(). Never throws.
 */
export async function download(): Promise<UpdaterStatus> {
  if (!updaterSupported() || phase !== "available") return getStatus();
  if (!downloadInFlight) {
    currentOperationSilent = false;
    currentOperation = "download";
    phase = "downloading";
    lastError = null;
    downloadInFlight = activeAutoUpdater
      .downloadUpdate()
      .then(() => {
        // The "update-downloaded" listener sets phase "staged".
      })
      .catch((err) => {
        const raw = err instanceof Error ? err.message : String(err);
        console.error("[updater] download failed:", raw);
        phase = "error";
        lastError = friendlyMessage(raw, "download");
      })
      .finally(() => {
        downloadInFlight = null;
      });
  }
  await downloadInFlight;
  return getStatus();
}

/**
 * Whether a background/focus re-check is due, throttled so window-focus
 * doesn't hammer the release feed. No timers — just a timestamp checked at
 * the call site (main.ts's "focus" listener).
 */
export function shouldBackgroundCheck(throttleMs = 4 * 60 * 60 * 1000): boolean {
  return Date.now() - lastCheckAt >= throttleMs;
}

/**
 * Quit and install the downloaded update. Only meaningful after an
 * "update-downloaded" event (stagedVersion set).
 */
export function installNow(): { applied: boolean; version?: string } {
  if (!updaterSupported() || !downloadedVersion) return { applied: false };
  const version = downloadedVersion;
  // Release the single-instance lock BEFORE quitAndInstall: on Linux,
  // AppImageUpdater spawns the NEW AppImage synchronously inside install(),
  // while this process is still alive and holding the lock — without this
  // release the relaunched instance loses the lock race and quits, leaving
  // the user with no window (update applied, app closed).
  app.releaseSingleInstanceLock();
  // isSilent=false keeps the NSIS UI defaults; isForceRunAfter=true relaunches
  // the app when the install completes. quitAndInstall calls app.quit(), so
  // the unsaved-changes close gate in main.ts still runs (unlike the old
  // app.exit(0) path, which skipped it).
  activeAutoUpdater.quitAndInstall(false, true);
  return { applied: true, version };
}
