// ──────────────────────────────────────────────────────────────────────────
// updater.ts — full-app auto-update via electron-updater (main process only)
//
// Replaces the former custom web-UI hot-swap engine (signed zip manifests,
// version pointers, health gate + rollback watchdog). Updates now ship as
// complete app releases on GitHub; electron-updater reads the release feed
// (latest.yml / latest-linux.yml, generated by electron-builder because
// electron-builder.yml declares a `publish` provider), downloads the new
// installer in the background, and installs it on restart.
//
// Platform support: Windows (NSIS) and Linux (AppImage). macOS auto-update
// requires a code-signed app (Squirrel.Mac refuses unsigned bundles), so it
// is disabled there until we ship signed/notarized builds — mac users update
// by downloading the DMG from GitHub Releases.
//
// Channels: electron-updater's default behavior — a stable install only sees
// stable releases; an install whose own version carries a prerelease suffix
// (e.g. 0.7.0-beta.1) also sees prereleases (allowPrerelease defaults from
// the current version). No separate channel setting to configure or drift.
// ──────────────────────────────────────────────────────────────────────────

import { app } from "electron";
// electron-updater is CJS; default-import + destructure for ESM interop.
import electronUpdater from "electron-updater";
import type { UpdaterStatus, UpdaterEventPayload } from "./bridge-types";

const { autoUpdater } = electronUpdater;

const MAC_UPDATE_HINT =
  "Automatic updates aren't available on macOS yet — download the latest release from GitHub.";

/**
 * Auto-update is active only in a packaged build with no vite dev server and
 * on a platform whose artifact format electron-updater can update unsigned.
 */
export function updaterSupported(): boolean {
  return (
    app.isPackaged &&
    !process.env.VITE_DEV_SERVER_URL &&
    process.platform !== "darwin"
  );
}

// In-memory status mirror for the renderer's getStatus() polling. The
// authoritative state lives inside electron-updater; this only tracks what
// the UI needs between events. `downloadedVersion` deliberately survives a
// later "update-not-available" check: the downloaded installer still applies
// on quit (autoInstallOnAppQuit), so reporting it staged stays truthful.
let phase: UpdaterStatus["phase"] = "idle";
let lastError: string | null = null;
let downloadedVersion: string | null = null;

let emitEvent: (event: UpdaterEventPayload) => void = () => {};
let checkInFlight: Promise<void> | null = null;

export function getStatus(): UpdaterStatus {
  return {
    currentVersion: app.getVersion(),
    stagedVersion: downloadedVersion,
    phase,
    error: lastError,
  };
}

/**
 * Wire the electron-updater listeners and the single event sink for renderer
 * push events. Call ONCE from main.ts before any checkForUpdates() call —
 * events always flow to this sink, never to a per-call callback (a per-call
 * parameter would advertise routing the implementation can't honor).
 */
export function initUpdater(onEvent: (event: UpdaterEventPayload) => void): void {
  emitEvent = onEvent;
  autoUpdater.autoDownload = true;
  // If the user quits without clicking the banner, install the downloaded
  // update on the way out rather than re-downloading next launch.
  autoUpdater.autoInstallOnAppQuit = true;
  autoUpdater.on("update-available", (info) => {
    phase = "downloading";
    emitEvent({ type: "available", version: info.version });
  });
  autoUpdater.on("update-not-available", () => {
    phase = "idle";
    emitEvent({ type: "uptodate" });
  });
  autoUpdater.on("update-downloaded", (info) => {
    phase = "staged";
    downloadedVersion = info.version;
    emitEvent({ type: "staged", version: info.version });
  });
  autoUpdater.on("error", (err) => {
    phase = "error";
    lastError = err instanceof Error ? err.message : String(err);
    emitEvent({ type: "error", message: lastError });
  });
}

/**
 * Check the GitHub release feed. Resolves once the CHECK completes — when an
 * update exists the download continues in the background (autoDownload) and
 * the "staged" event / getStatus().stagedVersion reports completion, so a
 * manual "Check for updates" never pins the renderer's spinner to a
 * multi-minute download. The returned status distinguishes the outcomes:
 * phase "downloading" (update found, fetching), "staged", "error", or "idle"
 * (up to date). Concurrent calls share one run. Never throws.
 */
export async function checkForUpdates(): Promise<UpdaterStatus> {
  if (!updaterSupported()) {
    // Manual checks on macOS get an honest pointer at GitHub Releases instead
    // of a silent idle status that reads as "you're up to date".
    if (app.isPackaged && process.platform === "darwin") {
      phase = "error";
      lastError = MAC_UPDATE_HINT;
    }
    return getStatus();
  }
  if (!checkInFlight) {
    phase = "checking";
    lastError = null;
    checkInFlight = (async () => {
      const result = await autoUpdater.checkForUpdates();
      // The check itself is done; don't await the download — just make sure
      // its rejection is observed (the "error" listener records the failure).
      result?.downloadPromise?.catch(() => {});
      // No update → the "update-not-available" listener already set idle.
    })()
      .catch((err) => {
        // The "error" listener above already recorded phase/lastError for
        // emitter-reported failures; this also catches pre-emitter throws.
        phase = "error";
        lastError = err instanceof Error ? err.message : String(err);
      })
      .finally(() => {
        checkInFlight = null;
      });
  }
  await checkInFlight;
  return getStatus();
}

/**
 * Quit and install the downloaded update. Only meaningful after an
 * "update-downloaded" event (stagedVersion set).
 */
export function installNow(): { applied: boolean; version?: string } {
  if (!updaterSupported() || !downloadedVersion) return { applied: false };
  const version = downloadedVersion;
  // Release the single-instance lock BEFORE quitAndInstall: on Linux,
  // AppImageUpdater spawns the NEW AppImage synchronously inside install(),
  // while this process is still alive and holding the lock — without this
  // release the relaunched instance loses the lock race and quits, leaving
  // the user with no window (update applied, app closed).
  app.releaseSingleInstanceLock();
  // isSilent=false keeps the NSIS UI defaults; isForceRunAfter=true relaunches
  // the app when the install completes. quitAndInstall calls app.quit(), so
  // the unsaved-changes close gate in main.ts still runs (unlike the old
  // app.exit(0) path, which skipped it).
  autoUpdater.quitAndInstall(false, true);
  return { applied: true, version };
}
