import { writeFile, unlink, rename } from "node:fs/promises";
import { join, dirname, basename, resolve } from "node:path";
import { run } from "./exec";

/**
 * Strip all annotations from a PDF using qpdf.
 *
 * Chromium embeds internal link annotations (from HTML `id` attributes)
 * that are not permitted in PDF/X output. Removing them before Ghostscript
 * prevents the "Annotation not TrapNet or PrinterMark" warning and keeps
 * the output in strict PDF/X compliance.
 */
export async function stripAnnotations(pdfPath: string): Promise<void> {
  const tmp = `${pdfPath}.stripped.pdf`;
  await run("qpdf", [pdfPath, tmp, "--flatten-annotations=all"]);
  await rename(tmp, pdfPath);
}

type PdfxFlavor = "x1a" | "x3";

/**
 * Generate the PostScript definition file for PDF/X output intent + GCR.
 */
export function makePdfxDefPs(params: {
  iccPath: string;
  pdfx: PdfxFlavor;
  title: string;
  maxTac?: number;
}): string {
  const pdfxVersion = params.pdfx === "x3" ? "PDF/X-3:2002" : "PDF/X-1:2001";
  const pdfxConformance = params.pdfx === "x1a" ? "PDF/X-1a:2001" : null;
  const outputConditionId = "CGATS21_CRPC1";
  const maxTacNorm = ((params.maxTac ?? 240) / 100).toFixed(1);
  const normalizedIccPath = params.iccPath.replace(/\\/g, "/");
  const iccComponents = 4;
  const docInfoConformance = pdfxConformance
    ? `/GTS_PDFXConformance (${pdfxConformance})\n`
    : "";

  return `
%!
% pdfx_def.ps generated by print-md
% Based on the Ghostscript PDF/X approach with custom GCR for TAC limiting

/ICCProfile (${normalizedIccPath}) def

% Maximum TAC = ${maxTacNorm} (${params.maxTac ?? 240}%)
/MaxTAC ${maxTacNorm} def

% UCR (Undercolor Removal) - aggressive GCR to reduce CMY in dark areas
% Takes K value, returns amount to subtract from CMY
/UCR {
  % For dark colors, remove more CMY
  dup 0.2 gt {
    0.2 sub 1.5 mul  % Remove 150% of K above 0.2 from CMY
    1 min 0 max
  } {
    pop 0
  } ifelse
} bind def

% BG (Black Generation) - standard K generation
/BG {
  % Pass through K value
} bind def

% Set UCR and BG functions for color conversion
<< /UCRFunction { UCR } /BGFunction { BG } >> setpagedevice

[/Title (${params.title})
/GTS_PDFXVersion (${pdfxVersion})
${docInfoConformance}/DOCINFO pdfmark

[/_objdef {icc_PDFX} /type /stream /OBJ pdfmark
[{icc_PDFX} << /N ${iccComponents} >> /PUT pdfmark
[{icc_PDFX} ICCProfile (r) file /PUT pdfmark

[/_objdef {OutputIntent_PDFX} /type /dict /OBJ pdfmark

[{OutputIntent_PDFX} <<
  /Type /OutputIntent
  /S /GTS_PDFX
  /OutputConditionIdentifier (${outputConditionId})
  /OutputCondition (${outputConditionId})
  /Info (${params.title})
  /RegistryName (http://www.color.org)
  /DestOutputProfile {icc_PDFX}
>> /PUT pdfmark

[{Catalog} << /OutputIntents [ {OutputIntent_PDFX} ] >> /PUT pdfmark
`;
}

/**
 * Convert an RGB PDF to CMYK PDF/X using Ghostscript.
 */
export async function convertToPdfxCmyk(
  inputPdf: string,
  outPdf: string,
  config: {
    iccPath: string;
    pdfx: PdfxFlavor;
    title?: string;
    maxTac?: number;
  }
): Promise<void> {
  const iccPath = resolve(config.iccPath);
  const tmpDef = join(dirname(outPdf), `.pdfx_def_${Date.now()}.ps`);
  await writeFile(
    tmpDef,
    makePdfxDefPs({
      iccPath,
      pdfx: config.pdfx,
      title: config.title ?? basename(outPdf),
      maxTac: config.maxTac,
    }),
    "utf8"
  );

  const args = [
    "-dSAFER",
    `--permit-file-read=${iccPath}`,
    "-dBATCH",
    "-dNOPAUSE",
    "-sDEVICE=pdfwrite",
    "-dPDFX",
    "-dCompatibilityLevel=1.3",
    "-dEmbedAllFonts=true",
    "-dSubsetFonts=true",
    "-dCompressFonts=true",
    "-dDetectDuplicateImages=true",
    "-dDownsampleColorImages=false",
    "-dDownsampleGrayImages=false",
    "-dDownsampleMonoImages=false",
    "-sProcessColorModel=DeviceCMYK",
    "-sColorConversionStrategy=CMYK",
    "-dOverrideICC=true",
    "-sDefaultRGBProfile=/usr/share/color/icc/ghostscript/srgb.icc",
    `-sOutputICCProfile=${iccPath}`,
    `-sOutputFile=${outPdf}`,
    tmpDef,
    inputPdf,
  ];

  await run("gs", args);
  await unlink(tmpDef).catch(() => {});
}
