/**
 * Files/dialog capability (SFE-P5c1, D10's named bounded context
 * "files/dialog"). Replaces `api.fs.*`/`api.dialog.*`/`api.shell.*` (deleted
 * `src/routes/api/{fs,dialog,shell}/**` HTTP routes) with typed IPC through
 * the one shared `bridge()` accessor — the same shape every other
 * capability module uses (SFE-P5b).
 *
 * SFE-P5b's capability map collapsed `files/dialog` to `api.fs`/`api.dialog`
 * called directly, because that run's ONLY real consumer (`EditorBuffer`'s
 * `readFile`/`writeFile`/`statFile`) was already reachable through plain
 * HTTP with zero added logic. This run gives the bounded context its own
 * module for real: the transport underneath changed from `fetch` to IPC, and
 * every one of this namespace's ~20 call sites across `FileTree.svelte`,
 * `ProjectsListBody.svelte`, `GitHubDialog.svelte`, `NewProjectWizard.svelte`,
 * `MediaPanel.svelte`, `EditorToolbar.svelte`, `+page.svelte`, and others
 * needs a new call site anyway — a plain function per operation, 1:1 named
 * after the deleted `api.fs.*`/`api.dialog.*`/`api.shell.*` method it
 * replaces, so every migrated call site is a name/import swap, not a
 * redesign.
 *
 * `shell.*` is grouped here (not a separate module) per the capability map's
 * own read: "shell | files/dialog (OS shell integration)" — `openExternal`/
 * `showInFolder` share the "acting on a file/path the author is looking at"
 * shape with the rest of this bounded context, and neither has any real
 * connection to another named D10 axis.
 *
 * Error semantics (run rule 2): every function here scrubs the Electron IPC
 * transport prefix (`friendlyHostError`) off a rejection's message before
 * re-throwing, so a caller's existing `e instanceof Error ? e.message :
 * String(e)` handling keeps showing the same author-facing text the deleted
 * HTTP routes used to send as the response body — `api.ts`'s `post`/`get`
 * helpers already discarded the HTTP status code and kept only that text, so
 * no caller ever branched on status; preserving the message string is what
 * preserves the caller's observable behavior across the transport change.
 *
 * Relative imports (not the `$lib` alias) for `bridge`/`friendlyHostError`/
 * `FileStat`/`FileWriteResult`: `contract.ts` type-imports `DirEntry`/
 * `ProjectFileEntry` back from this module (the same deliberate
 * "pure-forwarding-module survives because `ElectronBridge` needs its DTOs"
 * exception `editor-projection-capability.ts` established — see that file's
 * own relative imports), which makes this file reachable from
 * `tsc -p electron/tsconfig.json` via `electron/main.ts` →
 * `src/lib/persistence-failures.ts` → `contract.ts` → here. That program has
 * no `$lib` alias configured (SvelteKit's alias is generated by `svelte-kit
 * sync` into a program this one doesn't share), so a `$lib/...` specifier
 * fails to resolve there even though it resolves fine under the SPA's own
 * tsconfig — confirmed by actually running `bun run typecheck`, which is
 * exactly the failure restoring `electron/types.d.ts`'s `Window.electron`
 * block (SFE-P5c1 correction, see that file's header) also depended on.
 */
import { bridge } from "../platform/bridge";
import { friendlyHostError } from "../errors";
import type { FileStat, FileWriteResult } from "../platform/contract";

export interface DirEntry {
  name: string;
  path: string;
  isDir: boolean;
}

export interface ProjectFileEntry {
  md: string[];
  css: string[];
}

async function call<T>(op: Promise<T>): Promise<T> {
  try {
    return await op;
  } catch (e) {
    throw new Error(friendlyHostError(e instanceof Error ? e.message : String(e)));
  }
}

// ── fs ───────────────────────────────────────────────────────────────────

/** Read a file as UTF-8 text. Path must be absolute. */
export async function readFile(filePath: string): Promise<string> {
  return call(bridge().fs.readFile(filePath));
}

/**
 * Write UTF-8 content to a file. Path must be absolute. Triggers
 * auto-snapshot/sync debounce if the file is inside the open project.
 * Returns `{ mtimeMs }` of the post-write stat.
 */
export async function writeFile(filePath: string, content: string): Promise<FileWriteResult> {
  return call(bridge().fs.writeFile(filePath, content));
}

/** Stat a file. Returns `{ exists: false }` instead of throwing when absent. */
export async function statFile(filePath: string): Promise<FileStat> {
  return call(bridge().fs.statFile(filePath));
}

/** List the immediate entries of a directory. Path must be absolute. */
export async function listDir(dirPath: string): Promise<DirEntry[]> {
  return call(bridge().fs.listDir(dirPath));
}

/** List top-level `.md`/`.css` files in a project directory. */
export async function listProjectFiles(projectDir: string): Promise<ProjectFileEntry> {
  return call(bridge().fs.listProjectFiles(projectDir));
}

/** Create a new file under `dir`. Fails if a file already exists there. */
export async function createFile(dir: string, name: string, content = ""): Promise<{ path: string; mtimeMs: number }> {
  return call(bridge().fs.createFile(dir, name, content));
}

/** Create a new folder under `dir`. Fails if something already exists there. */
export async function createFolder(dir: string, name: string): Promise<{ path: string }> {
  return call(bridge().fs.createFolder(dir, name));
}

/** Rename a file/folder in place (same parent dir, new name). */
export async function renamePath(path: string, newName: string): Promise<{ path: string }> {
  return call(bridge().fs.renamePath(path, newName));
}

/**
 * Delete a file or folder (recursive). When the project has version history
 * the host snapshots the working tree first so the deleted content stays
 * recoverable through Version History; rejects WITHOUT deleting if that
 * safety snapshot fails.
 */
export async function deletePath(path: string, projectDir: string): Promise<{ ok: true }> {
  return call(bridge().fs.deletePath(path, projectDir));
}

// ── dialog ───────────────────────────────────────────────────────────────

/** Open native directory picker. Resolves null when cancelled. */
export async function openDirectory(): Promise<string | null> {
  return call(bridge().dialog.openDirectory());
}

/** Open native PDF save dialog. Resolves null when cancelled. */
export async function savePdf(defaultName?: string): Promise<string | null> {
  return call(bridge().dialog.savePdf(defaultName));
}

/** Open native single image file picker. Resolves null when cancelled. */
export async function pickImageFile(): Promise<string | null> {
  return call(bridge().dialog.pickImageFile());
}

/** Native open dialog for the publish artifact (PDF). Null when cancelled. */
export async function pickPdfFile(): Promise<string | null> {
  return call(bridge().dialog.pickPdfFile());
}

/** Open native multi-select image file picker. Resolves [] when cancelled. */
export async function pickImageFiles(): Promise<string[]> {
  return call(bridge().dialog.pickImageFiles());
}

// ── shell ────────────────────────────────────────────────────────────────

/** Open a URL in the system browser. */
export async function openExternal(url: string): Promise<{ ok: true }> {
  return call(bridge().shell.openExternal(url));
}

/** Reveal a file in the OS file manager. */
export async function showInFolder(filePath: string): Promise<{ ok: true }> {
  return call(bridge().shell.showInFolder(filePath));
}
